/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zyl_ndk_NdkJniUtils */

#ifndef _Included_com_zyl_ndk_NdkJniUtils
#define _Included_com_zyl_ndk_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zyl_ndk_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zyl_ndk_NdkJniUtils_getCLanguageString
        (JNIEnv *env, jobject obj) {
    return (*env)->NewStringUTF(env, "你好，ndk，我来了");
}

#ifdef __cplusplus
}
#endif
#endif
